version: "3.4"

services:
  aem6.2-author:
    image: cheproximity/aem-author:aem-6.2
    ports:
      - "4502:4502"
    volumes:
      - ./logs:/opt/aem/author/crx-quickstart/logs
      - authorRepo:/opt/aem/author/crx-quickstart/repository
  volumes:
    authorRepo:
      name: 6-2-author-repo