version: "3.4"

services:
  aem6_2-publisher:
    image: cheproximity/aem-publisher:aem-6.2
    container_name: my-aem6_2-publisher
    ports:
      - "4503:4503"
    volumes:
        - ./publishLogs:/opt/aem/publish/crx-quickstart/logs:delegated
        - publishRepo:/opt/aem/publish/crx-quickstart/repository  
  aem6_2-author:
    image: cheproximity/aem-author:aem-6.2
    container_name: my-aem6_3-author
    ports:
      - "4502:4502"
    volumes:
        - ./authorLogs:/opt/aem/author/crx-quickstart/logs:delegated
        - authorRepo:/opt/aem/author/crx-quickstart/repository  
  dispatcher-aem6.2:
    image: cheproximity/aem-dispatcher:apache2.4.18
    container_name: my-aem6-2-dispatcher
    ports: 
      - "8080:80"
    depends_on:
      - aem6_2-publisher
    environment:
      - "APACHE_LOG_DIR=/var/log/apache2"
    volumes:
      - ./www:/var/www
      - ./vhosts:/etc/apache2/sites-enabled
      - ./conf:/etc/apache2/conf
      - ./logs:/var/log/apache2/
      - ./cache:/opt/aem/dispatcher/cache
volumes:
    publishRepo:
      name: 6-2-publish-repo
    authorRepo:
      name: 6-2-author-repo