version: "3.3"

services:
  web:
    build: .
    ports: 
      - "80:80"
    volumes:
      - www:/var/www
      - vhosts:/etc/apache2/sites-enabled
      - conf:/etc/apache2/conf
    privileged: true

volumes:
  www:
  vhosts:
  conf:


    